# eureka注册中心
server:
  port: 8080
spring:
  application:
    name: EUREKA
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mytestdb?serverTimezone=UTC&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8

    #数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #连接池名称，默认HikariPool-1
      pool-name: KevinHikariPool
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 12
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      #发送心跳
      connection-test-query: SELECT 1

mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.leyou.registry.entity

#eureka配置：访问注册中心： 127.0.0.1:8080/
eureka:
  client:
    service-url:
      # 注册中心的url
      defaultZone: http://127.0.0.1:8080/eureka/
      #defaultZone: http://127.0.0.1:8080/eureka/,http://127.0.0.1:8081/eureka/
    # 关闭从注册中心获取服务列表（默认true）
    fetch-registry: true
    # 注册中心未做集群，所以不将本服务注册到注册中心（默认true）
    register-with-eureka: false
  server:
    # 多久时间剔除一次失效服务
    eviction-interval-timer-in-ms: 60000
    # 关闭注册中心的自我保护机制（默认true）
    enable-self-preservation: false

logging:
  level:
    com.leyou.registry.mapper: debug
    root: info
