# item_server
server:
  port: 9000
spring:
  application:
    name: ITEM-SERVER
  # 配置数据源
  datasource:
    # 数据源类型
    driver-class-name: com.mysql.jdbc.Driver
    # 账号
    username: root
    # 密码
    password: root
    # 数据源地址
    url: jdbc:mysql://localhost:3306/darkhouse?serverTimezone=UTC&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
    # 数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # hikari数据源连接池
    hikari:
      #连接池名称，默认HikariPool-1
      pool-name: KevinHikariPool
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 12
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 10
      #空闲连接超时时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      # 只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放
      idle-timeout: 500000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 540000
      # 连接保活。心跳
      connection-test-query: SELECT 1

# mybatis配置
mybatis:
  # 映射文件地址
  mapper-locations: classpath:mapping/*.xml
  # pojo类地址
  type-aliases-package: com.leyou.item.entity
#eureka配置
eureka:
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://127.0.0.1:8080/eureka/
  instance:
    # 5秒发一次心跳
    lease-renewal-interval-in-seconds: 5
    # 超过15秒未发心跳，则解除注册
    lease-expiration-duration-in-seconds: 15