server:
  port: 8090
spring:
  application:
    name: GATEWAY
# eureka注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    # 默认自动拉取eureka注册列表。那么可以设置多久拉取一次服务，这里设置5秒拉取一次（默认30秒）
    registry-fetch-interval-seconds: 5

# Zuul配置
zuul:
  # 配置路由前缀
  prefix: /api
  routes:
    ITEM-SERVER: /item-server/**

